# -*- coding: utf-8 -*-
"""BHUVANESH_M_prime_numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GMoJvfhs4iaCGiKYwduxamOQl1K9S0Zh
"""

def is_prime(n):
    if n <= 1:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False
    limit = int(n ** 0.5) + 1
    for i in range(3, limit, 2):
        if n % i == 0:
            return False
    return True

def get_valid_integer(prompt):
    while True:
        user_input = input(prompt)
        try:
            value = int(user_input)
            if value <= 0:
                print("Error: Please enter a positive integer greater than 0.")
            else:
                return value
        except ValueError:
            print(f"Error: '{user_input}' is not a valid integer. Please try again.")
def main():
    print("--- Prime Number Range Finder (No Imports) ---")
    print("Please enter the start and end of the range.")

    while True:
        start_range = get_valid_integer("Enter start value: ")
        end_range = get_valid_integer("Enter end value:   ")
        if start_range > end_range:
            print("\nLogic Error: Start value cannot be greater than end value.")
            print("Please enter the range again.\n")
        else:
            break

    print(f"\nSearching for prime numbers between {start_range} and {end_range}...\n")

    primes_found = 0
    for num in range(start_range, end_range + 1):
        if is_prime(num):
            print(f"{num:<6}", end="")
            primes_found += 1
            if primes_found % 10 == 0:
                print()
    if primes_found % 10 != 0:
        print()

    if primes_found == 0:
        print("No prime numbers found in this range.")
    else:
        print(f"\nTotal prime numbers found: {primes_found}")

if __name__ == "__main__":
    main()