# -*- coding: utf-8 -*-
"""BHUVANESH_M_Open_Weather_Map .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rCbcJK4jdy1tnUPkq2A5lFhmw6oBNz6X
"""


import requests
import csv
import os
from datetime import datetime

def fetch_weather(city: str, api_key: str) -> dict:
    """Fetch weather data from OpenWeatherMap API for a given city."""
    url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}&units=metric"
    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()
        data = response.json()
        if data.get('cod') != 200:
            msg = data.get('message', 'Unknown error from API.')
            print(f"API error: {msg}")
            return None
        return data
    except requests.exceptions.RequestException as e:
        print(f"Network/API error: {e}")
        return None
    except Exception as e:
        print(f"Unexpected error: {e}")
        return None

def analyze_weather(weather_data: dict) -> str:
    """Analyze weather data and return a summary string."""
    try:
        temp = weather_data['main']['temp']
        wind = weather_data['wind']['speed']
        humidity = weather_data['main']['humidity']
        summary = []
        # Temperature category
        if temp <= 10:
            summary.append("Cold (≤10°C)")
        elif 11 <= temp <= 24:
            summary.append("Mild (11–24°C)")
        else:
            summary.append("Hot (≥25°C)")
        # Alerts
        if wind > 10:
            summary.append("High wind alert!")
        if humidity > 80:
            summary.append("Humid conditions!")
        return f"Temp: {temp}°C, Wind: {wind} m/s, Humidity: {humidity}%. " + " ".join(summary)
    except (KeyError, TypeError):
        return "Incomplete weather data."

def log_weather(city: str, filename: str, api_key: str):
    """Fetch, analyze, and log weather data to a CSV file."""
    weather = fetch_weather(city, api_key)
    if not weather:
        print(f"Could not fetch weather for '{city}'.")
        return
    summary = analyze_weather(weather)
    temp = weather.get('main', {}).get('temp', '')
    humidity = weather.get('main', {}).get('humidity', '')
    wind = weather.get('wind', {}).get('speed', '')
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    file_exists = os.path.isfile(filename)
    try:
        with open(filename, 'a', newline='', encoding='utf-8') as csvfile:
            writer = csv.writer(csvfile)
            if not file_exists:
                writer.writerow(['City', 'Temperature (°C)', 'Humidity (%)', 'Wind Speed (m/s)', 'Summary', 'Timestamp'])
            writer.writerow([city, temp, humidity, wind, summary, timestamp])
        print(f"Weather for '{city}' logged to '{filename}'.")
    except Exception as e:
        print(f"File error: {e}")

def main():
    import getpass
    print("OpenWeatherMap Weather Logger")
    city = input("Enter city name: ").strip()
    api_key = os.environ.get('OPENWEATHER_API_KEY')
    if not api_key:
        api_key = getpass.getpass("Enter your OpenWeatherMap API key: ").strip()
    if not city or not api_key:
        print("City name and API key are required.")
        return
    log_weather(city, 'weather_log.csv', api_key)

if __name__ == "__main__":
    main()

