# -*- coding: utf-8 -*-
"""BHUVANESH_M_age_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MpECLaiQ1n256uzJpxHvkb6WXhxRaX8I
"""

import datetime

def validate_and_calculate_birthdate():
    while True:
        try:
            birth_date_str = input("Please enter your birth date in mm/dd/yyyy format: ")
            birth_date = datetime.datetime.strptime(birth_date_str, "%m/%d/%Y").date()
            today = datetime.date.today()
            if birth_date > today:
                print("Error: Birth date cannot be in the future. Please try again.")
                continue
            age = today.year - birth_date.year - ((today.month, today.day) < (birth_date.month, birth_date.day))
            european_format_date = birth_date.strftime("%d/%m/%Y")

            print(f"\nValid birth date entered: {birth_date_str}")
            print(f"Your current age is: {age} years")
            print(f"Your birth date in European format is: {european_format_date}")
            break

        except ValueError as e:
            print(f"Error: Invalid date format or value. Please ensure the date is valid and in mm/dd/yyyy format. ({e})")
            print("Example: For August 15, 1947, enter 15/08/1947.")
        except Exception as e:
            print(f"An unexpected error occurred: {e}")

validate_and_calculate_birthdate()