# -*- coding: utf-8 -*-
"""BHUVANESH_M_Student_Marks_Processor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vTLV5_iDewpBzdh1jnB_KuHDotH6Mzc5
"""

import numpy as np
import sys
import os

EXAM_WEIGHT = 0.7
COURSEWORK_WEIGHT = 0.3
VALID_GRADE_RANGES = [
    (70, 100, 'A'),
    (60, 69, 'B'),
    (50, 59, 'C'),
    (40, 49, 'D'),
    (0, 39, 'F')
]

def determine_grade(overall_mark):
    """Determine the grade based on the overall mark."""
    for low, high, grade in VALID_GRADE_RANGES:
        if low <= overall_mark <= high:
            return grade
    return 'F'

def validate_mark(mark, mark_type):
    """Validate that a mark is a number between 0 and 100."""
    try:
        mark_val = float(mark)
        if not (0 <= mark_val <= 100):
            raise ValueError(f"{mark_type} mark must be between 0 and 100.")
        return mark_val
    except ValueError as e:
        if "must be between" in str(e):
            raise e
        else:
            raise ValueError(f"{mark_type} mark must be a valid number.")

def read_student_data(input_file):
    """Read and validate student data from the input file."""
    records = []
    line_num = 0

    try:
        with open(input_file, 'r') as f:
            for line in f:
                line_num += 1
                line = line.strip()
                if not line:
                    continue

                parts = line.split()
                if len(parts) != 3:
                    raise ValueError(f"Line {line_num}: Expected 3 fields (reg_num exam_mark coursework_mark), got {len(parts)}.")

                reg_num, exam_str, coursework_str = parts
                if not reg_num:
                    raise ValueError(f"Line {line_num}: Registration number cannot be empty.")

                exam_mark = validate_mark(exam_str, "Exam")
                coursework_mark = validate_mark(coursework_str, "Coursework")

                overall = EXAM_WEIGHT * exam_mark + COURSEWORK_WEIGHT * coursework_mark
                grade = determine_grade(overall)

                records.append((reg_num, exam_mark, coursework_mark, overall, grade))

    except FileNotFoundError:
        print(f"Error: Input file '{input_file}' not found.", file=sys.stderr)
        sys.exit(1)
    except IOError as e:
        print(f"Error reading file '{input_file}': {e}", file=sys.stderr)
        sys.exit(1)
    except ValueError as e:
        print(f"Data error in file '{input_file}': {e}", file=sys.stderr)
        sys.exit(1)

    if not records:
        print(f"Warning: No valid records found in '{input_file}'.", file=sys.stderr)

    return records

def create_numpy_array(records):
    """Create a structured NumPy array from validated records."""
    if not records:
        return np.array([], dtype=[
            ('reg_num', 'U20'),
            ('exam_mark', 'f4'),
            ('coursework_mark', 'f4'),
            ('overall_mark', 'f4'),
            ('grade', 'U2')
        ])

    dtype = [
        ('reg_num', 'U20'),
        ('exam_mark', 'f4'),
        ('coursework_mark', 'f4'),
        ('overall_mark', 'f4'),
        ('grade', 'U2')
    ]

    arr = np.array(records, dtype=dtype)
    return arr

def sort_by_overall_mark(arr):
    """Sort the array by overall mark in descending order."""
    return np.sort(arr, order='overall_mark')[::-1]

def write_output_file(arr, output_file):
    """Write sorted results to the output file."""
    try:
        with open(output_file, 'w') as f:
            f.write(f"{'Reg No':<15} {'Exam':<8} {'Course':<8} {'Overall':<8} {'Grade'}\n")
            f.write("-" * 50 + "\n")
            for record in arr:
                f.write(f"{record['reg_num']:<15} "
                        f"{record['exam_mark']:<8.1f} "
                        f"{record['coursework_mark']:<8.1f} "
                        f"{record['overall_mark']:<8.1f} "
                        f"{record['grade']}\n")
    except IOError as e:
        print(f"Error writing to output file '{output_file}': {e}", file=sys.stderr)
        sys.exit(1)

def display_summary_statistics(arr):
    """Display grade counts and average overall mark."""
    if arr.size == 0:
        print("No data to summarize.")
        return

    grades, counts = np.unique(arr['grade'], return_counts=True)
    grade_summary = dict(zip(grades, counts))

    print("\nGrade Summary:")
    print("-" * 20)
    for grade in ['A', 'B', 'C', 'D', 'F']:
        count = grade_summary.get(grade, 0)
        print(f"Grade {grade}: {count}")

    average_mark = np.mean(arr['overall_mark'])
    print(f"\nAverage Overall Mark: {average_mark:.2f}")

def main():
    if len(sys.argv) != 3:
        print("Usage: python student_marks.py <input_file> <output_file>", file=sys.stderr)
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2]

    if not os.path.isfile(input_file):
        print(f"Error: Input file '{input_file}' does not exist.", file=sys.stderr)
        sys.exit(1)

    records = read_student_data(input_file)
    arr = create_numpy_array(records)
    sorted_arr = sort_by_overall_mark(arr)
    write_output_file(sorted_arr, output_file)
    display_summary_statistics(sorted_arr)

    print(f"\nProcessed {len(sorted_arr)} student records.")
    print(f"Results written to '{output_file}'.")

if __name__ == "__main__":
    main()